---
# Depends on: sbunets.yml
- set_fact:
    aws_vpc_igw_name: "ANSIBLE {{ aws_resource_tag_slug }} internet gateway"
- name: Create an internet gateway for the VPC
  ec2_vpc_igw:
    vpc_id: "{{ aws_vpc_id }}"
    state: present
    aws_access_key: "{{ aws_api_access_key }}"
    aws_secret_key: "{{ aws_api_secret_key }}"
    state: present
    region: "{{ aws_vpc_region }}"
    tags: "{{ aws_billing_tags | combine({'Name': aws_vpc_igw_name })  }}"
  register: igw_result

- debug:
    var: igw_result
    verbosity: 1

- set_fact:
    aws_vpc_igw_id: "{{ igw_result.gateway_id }}"
    aws_vpc_internet_gateway_id: "{{ igw_result.gateway_id }}"
- debug:
    var: aws_vpc_igw_id
    verbosity: 1
