---
# Order of tasks is not trivial. Each compoenent depends on the one previous to it.
- import_tasks: ./vpc.yml
- import_tasks: ./subnets.yml
- import_tasks: ./internet_gateway.yml
- include_tasks: ./nat_gateway.yml
  when: aws_vpc_private_subnets | length > 0
    and aws_vpc_private_subnets is not string
- import_tasks: ./routes.yml
