---
# Order of tasks is not trivial. Each compoenent depends on the one previous to it.
- import_tasks: ./vpc.yml
- import_tasks: ./subnets.yml
- import_tasks: ./internet_gateway.yml
- import_tasks: ./nat_gateway.yml
- import_tasks: ./routes.yml
