---
# Depends on: sbunets.yml

# ec2_vpc_nat_gateway doesnt support tags yet:
# - See: https://github.com/ansible/ansible/issues/44339
# - See: https://github.com/ansible/ansible/pull/46624

- name: Create an NAT gateway so instances on the private network can access the internet
  ec2_vpc_nat_gateway:
    aws_access_key: "{{ aws_api_access_key }}"
    aws_secret_key: "{{ aws_api_secret_key }}"
    region: "{{ aws_vpc_region }}"
    # tags: ec2_vpc_nat_gateway doesnt support tags yet... See ec2_tag task below
    if_exist_do_not_create: true
    state: present
    subnet_id: "{{ aws_vpc_public_subnet_id_list[0] }}"    # just use the ID of the first public subnet. It's pretty arbitrary
  register: nat_gateway_result

- debug:
    var: nat_gateway_result
    verbosity: 1

- set_fact:
    aws_vpc_nat_gateway_id: "{{ nat_gateway_result.nat_gateway_id }}"
    aws_vpc_ngw_id: "{{ nat_gateway_result.nat_gateway_id }}"
    aws_vpc_nat_gateway_addresses: "{{ nat_gateway_result.nat_gateway_addresses }}"

- debug:
    var: aws_vpc_nat_gateway_id
    verbosity: 1

- debug:
    var: aws_vpc_nat_gateway_addresses
    verbosity: 1

- set_fact:
    _nat_gateway_name: "{{ aws_resource_tag_slug + ' ' + aws_resource_env_slug + '  NAT gateway ' + aws_resource_name_suffix | trim}}"
    _nat_gateway_ansible_host_id: "{{ aws_resource_tag_slug.lower() }}-{{ aws_resource_env_slug.lower() }}-ngw"

- name: Tag the NAT gateway
  ec2_tag:
    aws_access_key: "{{ aws_api_access_key }}"
    aws_secret_key: "{{ aws_api_secret_key }}"
    region: "{{ aws_vpc_region }}"
    resource: "{{ aws_vpc_nat_gateway_id }}"
    state: present
    tags: "{{ aws_billing_tags | combine({'Name': _nat_gateway_name,
    'ansible-host-id': _nat_gateway_ansible_host_id }) }}"
  register: ngw_tag_result

- debug:
    var: ngw_tag_result
    verbosity: 1

- set_fact:
    _ngw_eip_name: "{{ aws_resource_tag_slug + ' ' + aws_resource_env_slug + '  NAT gateway EIP ' + aws_resource_name_suffix | trim}}"

- name: Tag the elastic IP(s) created by the NAT gateway
  ec2_tag:
    aws_access_key: "{{ aws_api_access_key }}"
    aws_secret_key: "{{ aws_api_secret_key }}"
    region: "{{ aws_vpc_region }}"
    resource: "{{ item.allocation_id }}"
    state: present
    tags: "{{ aws_billing_tags | combine({'Name': _ngw_eip_name }) }}"
  with_items: "{{ aws_vpc_nat_gateway_addresses }}"
  register: ngw_eip_tag_result

- debug:
    var: ngw_eip_tag_result
    verbosity: 1
