---
# Depends on: internet_gateway.yml
# Depends on: nat_gateway.yml


#### *** WARNING - ec2_vpc_route_table have a bug, or may have undocumented idempotency behaviour  ****
#### *** Either way, it dosn't seem to be idempotent out of the box, unless you specify its ID.
#### *** No other ec2 module requires this.
#### *** Running the task without an ID just keeps creating resources.
#### *** See https://github.com/ansible/ansible/issues/59863 ***
#### *** See https://github.com/ansible/ansible/issues/21299 ***

- name: Gather route table info
  ec2_vpc_route_table_info:
    aws_access_key: "{{ aws_api_access_key }}"
    aws_secret_key: "{{ aws_api_secret_key }}"
    region: "{{ aws_vpc_region }}"
    filters:
      vpc_id: "{{ aws_vpc_id }}"
  register: route_table_info_result

- debug:
    var: route_table_info_result
  when: aws_dump_registered_vars == true

- name: Get the default route table ID
  set_fact:
    primary_route_table_id: "{%
      for tbl in route_table_info_result.route_tables %}{%
        for assoc in tbl.associations %}{%
          if assoc.main == true
            %}{{ assoc.route_table_id }}{%
          endif %}{%
        endfor %}{%
      endfor
      %}"

- debug:
    var: primary_route_table_id
  when: aws_dump_registered_vars == true

- name: Configure the primary/public route table, which automatically gets created along with new VPCs
  ec2_vpc_route_table:
    aws_access_key: "{{ aws_api_access_key }}"
    aws_secret_key: "{{ aws_api_secret_key }}"
    vpc_id: "{{ aws_vpc_id }}"
    region: "{{ aws_vpc_region }}"
    route_table_id: "{{ primary_route_table_id }}"
    tags: "{{ aws_billing_tags |combine({'Name': 'ANSIBLE ' + aws_resource_tag_slug + ' public routes'})  }}"
    subnets: "{{ public_subnet_result['results'] | map(attribute='subnet') | map(attribute='id') | list }}"
    routes:
      - dest: 0.0.0.0/0
        gateway_id: "{{ igw_result.gateway_id }}"
  register: public_route_table_result

- debug:
    var: public_route_table_result
  when: aws_dump_registered_vars == true

- name: Add private route table
  ec2_vpc_route_table:
    aws_access_key: "{{ aws_api_access_key }}"
    aws_secret_key: "{{ aws_api_secret_key }}"
    vpc_id: "{{ aws_vpc_id }}"
    region: "{{ aws_vpc_region }}"
    tags: "{{ aws_billing_tags |combine({'Name': 'ANSIBLE ' + aws_resource_tag_slug + ' private routes' })  }}"
    subnets: "{{ private_subnet_result['results'] | map(attribute='subnet') | map(attribute='id') | list }}"
    routes:
      - dest: 0.0.0.0/0
        gateway_id: "{{ nat_gateway_result.nat_gateway_id }}"
  when: (route_table_info_result.route_tables | length()) < 2
  register: private_route_table_result     #  After this is created, the info will be accessible from "route_table_info_result" above.

- debug:
    var: private_route_table_result
  when: private_route_table_result is defined
    and aws_dump_registered_vars == true
