---
# Depends on: internet_gateway.yml
# Depends on: nat_gateway.yml


#### *** WARNING - ec2_vpc_route_table have a bug, or may have undocumented idempotency behaviour  ****
#### *** Either way, it dosn't seem to be idempotent out of the box, unless you specify its ID.
#### *** No other ec2 module requires this.
#### *** Running the task without an ID just keeps creating resources.
#### *** See https://github.com/ansible/ansible/issues/59863 ***
#### *** See https://github.com/ansible/ansible/issues/21299 ***

- name: Gather route table info
  ec2_vpc_route_table_info:
    aws_access_key: "{{ aws_api_access_key }}"
    aws_secret_key: "{{ aws_api_secret_key }}"
    region: "{{ aws_vpc_region }}"
    filters:
      vpc_id: "{{ aws_vpc_id }}"
  register: route_table_info_result

- debug:
    var: route_table_info_result
    verbosity: 1

- name: Get the ID of the main route table
  set_fact:
    primary_route_table_id: "{%
      for tbl in route_table_info_result.route_tables %}{%
        for assoc in tbl.associations %}{%
          if assoc.main == true
            %}{{ assoc.route_table_id }}{%
          endif %}{%
        endfor %}{%
      endfor
      %}"

- debug:
    var: primary_route_table_id
    verbosity: 1

- set_fact:
    aws_vpc_public_route_table_name: "{{ aws_resource_tag_slug + ' ' + aws_resource_env_slug + ' public routes ' + aws_resource_name_suffix | trim }}"

- name: Configure the main route table {{ primary_route_table_id }}, which was automatically created with our new VPC, for public routes
  ec2_vpc_route_table:
    aws_access_key: "{{ aws_api_access_key }}"
    aws_secret_key: "{{ aws_api_secret_key }}"
    vpc_id: "{{ aws_vpc_id }}"
    region: "{{ aws_vpc_region }}"
    state: present
    lookup: id
    route_table_id: "{{ primary_route_table_id }}"
    tags: "{{ aws_billing_tags |combine({'Name': aws_vpc_public_route_table_name}) }}"
    purge_tags: no
    subnets: "{{ aws_vpc_public_subnet_id_list }}"
    purge_subnets: no
    routes:
      - dest: 0.0.0.0/0
        gateway_id: "{{ aws_vpc_igw_id }}"
    purge_routes: no
  register: public_route_table_result

- debug:
    var: public_route_table_result
    verbosity: 1

- set_fact:
    aws_vpc_private_route_table_name: "{{ aws_resource_tag_slug + ' ' + aws_resource_env_slug + ' private routes ' + aws_resource_name_suffix | trim }}"

- name: Configure the private route table
  ec2_vpc_route_table:
    aws_access_key: "{{ aws_api_access_key }}"
    aws_secret_key: "{{ aws_api_secret_key }}"
    vpc_id: "{{ aws_vpc_id }}"
    region: "{{ aws_vpc_region }}"
    state: present
    lookup: tag
    tags:
      Name: "{{ aws_vpc_private_route_table_name }}"  # Purposely not assigning any extra tags to private route, since this is our only handle on it.
    purge_tags: no
    subnets: "{{ aws_vpc_private_subnet_id_list }}"
    purge_subnets: no
    routes:
      - dest: 0.0.0.0/0
        gateway_id: "{{ aws_vpc_nat_gateway_id }}"
    purge_routes: no
  register: private_route_table_result
  when: aws_vpc_private_subnets | length > 0
    and aws_vpc_private_subnets is not string

- debug:
    var: private_route_table_result
    verbosity: 1
  when: private_route_table_result is defined
