----
- set_fact:
    _vpc_ansible_host_id: "{{ aws_resource_tag_slug.lower() }}-{{ aws_resource_env_slug.lower() }}-vpc"

- name: Create a VPC
  ec2_vpc_net:
    name: "{{ aws_resource_tag_slug + ' ' + aws_resource_env_slug + ' VPC ' + aws_resource_name_suffix | trim }}"
    cidr_block: "{{ aws_vpc_private_net_cidr }}"
    region: "{{ aws_vpc_region }}"
    tags: "{{ aws_billing_tags | combine({'ansible-host-id': _vpc_ansible_host_id}) }}"
    aws_access_key: "{{ aws_api_access_key }}"
    aws_secret_key: "{{ aws_api_secret_key }}"
    dns_hostnames: yes
    dns_support: yes
    multi_ok: no
    purge_cidrs: no
    state: present
    tenancy: default
  register: vpc_result

- debug:
    var: vpc_result
    verbosity: 1

- set_fact:
    aws_vpc_id: "{{ vpc_result.vpc.id }}"

- debug:
    var: aws_vpc_id
    verbosity: 1
